Repository Lustrel/money-management, pull requests merged in 2018-12, with the labels that each got.

#3 User CRUD
  config/packages/twig.yaml
  config/routes.yaml
  public/bundles/pugxautocompleter/js/autocompleter-jqueryui.js
  public/bundles/pugxautocompleter/js/autocompleter-select2.js
  src/Controller/CreateLoan.php
  src/Controller/RegisterUser.php
  src/Controller/User.php
  src/Controller/UsersController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/User.php
  src/Migrations/Version20181208014819.php
  templates/base.html.twig
  templates/bootstrap_4_layout.html.twig
  templates/create-user.html.twig
  templates/edit-user.html.twig
  templates/registerUser.html.twig
  templates/registerUserSuccess.html.twig
  templates/users.html.twig
Labels: WIP

#23 Add Installments report
  composer.json
  src/Controller/Installment.php
  src/Entity/Loan.php
  src/Migrations/Version20181220224405.php
  templates/installment/index.html.twig
  templates/installment/installments.html.twig
  templates/navbar.html.twig
Labels: high-priority

#24 Add "Installment's value" column to Loans list
  src/Entity/Loan.php
  templates/loan/index.html.twig
Labels: low-priority

#25 Rename all "Empréstimos" to "Produtos"
  src/Controller/Loan.php
  templates/access_not_allowed.html.twig
  templates/db_success_update.html.twig
  templates/fields.html.twig
  templates/list_users.html.twig
  templates/loan/index.html.twig
  templates/navbar.html.twig
  templates/notFound.html.twig
  templates/report_main.html.twig
  templates/your_template.json.twig
Labels: medium-priority

#26 Add app.json to configure Heroku Pipeline
  app.json
  composer.json
Labels: infra

#30 Add App\Service\Loan to reduce code complexity
  config/services.yaml
  src/Controller/Loan.php
  src/Repository/LoansRepository.php
  src/Service/Calculator.php
  src/Service/Loan.php
Labels: medium-priority

#33 Add partial payments for installments
  config/routes.yaml
  src/Controller/Customer.php
  src/Controller/Installment.php
  src/Controller/Loan.php
  src/Entity/Customer.php
  src/Migrations/Version20181227220958.php
  src/Repository/InstallmentsRepository.php
  src/Service/Installment.php
  templates/customer/index.html.twig
  templates/installment/new-loan-message.html.twig
  templates/installment/pay.html.twig
  templates/loan/index.html.twig
Labels: WIP

#34 Query LIKE to customers filter
  public/bundles/pugxautocompleter/js/autocompleter-jqueryui.js
  public/bundles/pugxautocompleter/js/autocompleter-select2.js
  src/Controller/Customer.php
  src/Repository/CustomersRepository.php
  src/Service/Customer.php
  templates/customer/index.html.twig
Labels: WIP
